name: Build and test nexus-casc-plugin

on:
  push:
    branches: [ master ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn -B verify --file pom.xml
      - run: mkdir staging && cp target/*.{k,j}ar staging
      - uses: actions/upload-artifact@v2
        with:
          name: nexus-casc-plugin
          path: staging
